config/routes.rb
Rails.application.routes.draw do
  get 'users/sessions'
  root to: "public/homes#top"
  get "/homes/about" => "public/homes#about", as: "about"
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  namespace :admin do
    get 'users', to: 'users#index'
    patch 'users/:id/withdraw',to: "users#withdraw", as: "users_withdraw"
    resources :tags, except: [:show]
    resources :fitness_gyms do
      resources :reviews, only: [:show, :destroy]
    end
  end

  scope module: :public do
    resources :fitness_gyms, only: [:show, :index, :create]
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end
    get 'users/unsubscribe'
    patch 'users/withdraw'
    
    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
    
    resources :users, only: [:show, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fitness_gym.rb
class FitnessGym < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  has_many :gym_tags, dependent: :destroy
  has_many :tags, through: :gym_tags
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :content, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode

  accepts_nested_attributes_for :tags

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tags(savebook_tags)
    # 現在のユーザーの持っているskillを引っ張ってきている
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 今fitness_gymが持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
    old_tags = current_tags - savebook_tags
    # 今回保存されたものと現在の差を新しいタグとする。新しいタグは保存
    new_tags = savebook_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      gym_tag = Tag.find_or_create_by(name:new_name)
      # 配列に保存
      self.tags << gym_tag
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Fitness_gym.where(title: content)
    elsif method == 'forward'
      Fitness_gym.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Fitness_gym.where('title LIKE ?', '%'+content)
    else
      Fitness_gym.where('title LIKE ?', '%'+content+'%')
    end
  end


  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/admin/fitness_gyms_controller.rb
class Admin::FitnessGymsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @fitness_gym = FitnessGym.new
  end

  def index
    @fitness_gyms = FitnessGym.all
  end
  
  def show
    @fitness_gym = FitnessGym.find(params[:id])
    @reviews = @fitness_gym.reviews
  end

  def edit
    @fitness_gym = FitnessGym.find(params[:id])
  end

  def create
    @fitness_gym = FitnessGym.new(fitness_gym_params)
    if @fitness_gym.save
      redirect_to admin_fitness_gyms_path
    else
      render :new
    end
  end

  def update
    @fitness_gym = FitnessGym.find(params[:id])
    if @fitness_gym.update(fitness_gym_params)
      redirect_to admin_fitness_gyms_path(@fitness_gyms)
    else
      render :edit
    end
  end

  def destroy
    fitness_gym = FitnessGym.find(params[:id])
    fitness_gym.destroy
    redirect_to admin_fitness_gyms_path
  end
  
  private

  def fitness_gym_params
    params.require(:fitness_gym).permit(:name, :content, :address, tag_ids: [])
  end
end

app/helpers/admin/fitness_gyms_helper.rb
module Admin::FitnessGymsHelper
end

app/helpers/fitness_gyms_helper.rb
module FitnessGymsHelper
end

app/views/admin/fitness_gyms/edit.html.erb
<div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">フィットネスジム投稿編集</h5>
      <div class="form-body p-4">
        <% if @fitness_gym.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @fitness_gym.errors.count %>件のエラーが発生しました
            </h6>
            <% @fitness_gym.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @fitness_gym,url: admin_fitness_gym_path, method: :patch do |f| %>
        <%= f.text_field :name, class: "form-control", placeholder: "ジム名" %>
          <div class="check_box">
            <span>タグ</span>
            <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
             <div>
               <%= tag.label do %>
                 <%= tag.check_box %>
                 <%= tag.text %>
               <% end %>
             </div>
           <% end %>
          </div>
          <div class="input-group mb-3 mt-4">
              <div class="input-group-prepend">
                <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-tenge-sign"></i></span>
              </div>
              <%= text_field_tag :zipcode, nil, class: "form-control", placeholder: "郵便番号" %>
            </div>
            <div class="input-group mb-3 mt-4">
              <div class="input-group-prepend">
                <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-location-dot"></i></span>
              </div>
              <%= f.text_field :address, class: "form-control", placeholder: "住所" %>
            </div>
            <%= f.text_area :content, class: "form-control", placeholder: "ジム説明" %>
          <%= f.submit '投稿' %>
          <%= link_to '一覧', admin_fitness_gyms_path(f) %>
          <%= link_to '削除', admin_fitness_gym_path(@fitness_gym), method: :delete %>
        <% end %>

app/views/admin/fitness_gyms/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h3>フィットネスジム一覧</h3>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>ジム名</th>
          <th>説明</th>
          <th></th>
          <th></th>
          <th colspan="5"></th>
        </tr>
      </thead>
      <% @fitness_gyms.each do |fitness_gym| %>
      <tbody>
        <tr>
          <td>
            <%= fitness_gym.name %>
          </td>
          <td>
            <%= fitness_gym.content %>
          </td>
          <td>
            <%= link_to 'ジム詳細', admin_fitness_gym_path(fitness_gym) %>
          </td>
          <td>
            <%= link_to '編集', edit_admin_fitness_gym_path(fitness_gym) %>
          </td>
          <td>
            <%= link_to '削除', admin_fitness_gym_path(fitness_gym), method: :delete %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  
  <div class="my-5">
    <%= link_to 'ジム登録', new_admin_fitness_gym_path %>
  </div>
</div>

app/views/admin/fitness_gyms/new.html.erb
<div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">フィットネスジム投稿</h5>
      <div class="form-body p-4">
        <% if @fitness_gym.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @fitness_gym.errors.count %>件のエラーが発生しました
            </h6>
            <% @fitness_gym.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @fitness_gym,url: admin_fitness_gyms_path do |f| %>
            <%= f.text_field :name, class: "form-control", placeholder: "ジム名" %>
              <div class="check_box">
                <span>タグ</span>
                <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                 <div>
                   <%= tag.label do %>
                     <%= tag.check_box %>
                     <%= tag.text %>
                   <% end %>
                 </div>
               <% end %>
              </div>
            <div class="input-group mb-3 mt-4">
              <div class="input-group-prepend">
                <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-tenge-sign"></i></span>
              </div>
              <%= text_field_tag :zipcode, nil, class: "form-control", placeholder: "郵便番号" %>
            </div>
            <div class="input-group mb-3 mt-4">
              <div class="input-group-prepend">
                <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-location-dot"></i></span>
              </div>
              <%= f.text_field :address, class: "form-control", placeholder: "住所" %>
            </div>
            <%= f.text_area :content, class: "form-control", placeholder: "ジム説明" %>
            <%= f.submit '投稿' %>
        <% end %>

app/views/admin/fitness_gyms/show.html.erb
<div class="container">
  <h1><%= @fitness_gym.name %></h1>
  <div class="mb-2 row">
    <span><i class="fa-solid fa-location-dot"></i> <%= @fitness_gym.address %></span>
  </div>
  <h4 class="mb-5">
    <%= @fitness_gym.content %>
  </h4>

  <% if @reviews.any? %>
    <% @reviews.each do |review| %>
      <div class="<%= review.id %>">
        <div id="post_raty_<%= review.id %>"></div>
        <script>
          // scriptファイルをどのidの部分に配置するかを指定
          document.querySelector('#post_raty_<%= review.id %>').innerHTML = '';
          raty(document.querySelector('#post_raty_<%= review.id %>'),
          {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            score: "<%= review.star %>",
            readOnly: true
          });
        </script>
        <div class="row">
          <div class="mb-3 my-3">
            <%= image_tag review.user.get_profile_image(50,50) %>
          </div>
          <div class="my-4 ml-3">
            <p>ユーザーネーム：<%= review.user.name %></p>
          </div>
        </div>
        <p>タイトル: <%= review.title %></p>
        <p>説明：<%= review.content %></p>
        <%= link_to 'レビュー詳細', admin_fitness_gym_review_path(review.fitness_gym,review) %>
      </div>
    <% end %>
  <% end %>
</div>