config/routes.rb
Rails.application.routes.draw do
  get 'users/sessions'
  root to: "public/homes#top"
  get "/homes/about" => "public/homes#about", as: "about"
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  namespace :admin do
    get 'users', to: 'users#index'
    patch 'users/:id/withdraw',to: "users#withdraw", as: "users_withdraw"
    resources :tags, except: [:show]
    resources :fitness_gyms do
      resources :reviews, only: [:show, :destroy]
    end
  end

  scope module: :public do
    resources :fitness_gyms, only: [:show, :index, :create]
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end
    get 'users/unsubscribe'
    patch 'users/withdraw'
    
    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
    
    resources :users, only: [:show, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gym_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :fitness_gyms, through: :gym_tags
  
  validates :name, presence: true

  scope :merge_fitness_gyms, -> (tags){ }
  
  def self.search_fitness_gyms_for(content, method)
    
    if method == 'perfect'
      tags = Tag.where(name: content)
    elsif method == 'forward'
      tags = Tag.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      tags = Tag.where('name LIKE ?', '%' + content)
    else
      tags = Tag.where('name LIKE ?', '%' + content + '%')
    end
    
    return tags.inject(init = []) {|result, tag| result + tag.gyms}
    
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
      if @tag.save
        redirect_to admin_tags_path, success: 'ポストを作成しました'
      else
        flash.now[:danger] = 'ポストを作成できませんでした'
        render :new
      end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    tag_names = params[:tag][:tag_names]
    if @tag.update(tag_params)
      if tag_names.present?
        tags = params[:tag][:tag_names].split("\n").map(&:strip).uniq
        create_or_update_tags(@tag, tags)
      end
      redirect_to admin_tags_path(@tag), success: 'ポストを更新しました'
    else
      flash.now[:danger] = 'ポストを更新できませんでした'
      render :edit
    end
  end

  def new
    @tag = Tag.new
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to '/admin/tags'
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end


end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="row no-gutters">
  <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
    <h5 class="text-dark bg-light p-4 mb-0">タグ編集</h5>
    <div class="form-body p-4">
      <%= form_with model: @tag,url: admin_tag_path, method: :patch do |tag| %>
        <h4>tag</h4>
        <div class="my-3">
          <%= tag.text_field :name %>
          <%= tag.submit '投稿' %>
          <%= link_to '一覧', admin_tags_path %>
          <%= link_to '削除', admin_tag_path(@tag), method: :delete %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h3>タグ一覧</h3>
    <table class="table table-hover table-inverse">
    　<thead>
        <tr>
        　<th>タグ名</th>
        　<th></th>
        　<th></th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <% Tag.all.each do |tag| %>
      <tbody>
        <tr>
          <td><%= tag.name %></td>
          <td>
            <%= link_to '編集', edit_admin_tag_path(tag) %>
          </td>
          <td>
            <%= link_to '削除', admin_tag_path(tag), method: :delete %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <div class="my-5">
    <%= link_to 'タグ登録', new_admin_tag_path %>
  </div>
</div>

app/views/admin/tags/new.html.erb
<div class="row no-gutters">
  <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
    <h5 class="text-dark bg-light p-4 mb-0">タグ投稿</h5>
    <div class="form-body p-4">
      <% if @tag.errors.any? %>
        <%= @tag.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @tag.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @tag,url: admin_tags_path do |f| %>
        <%= f.text_field :name %>
        <%= f.submit '投稿' %>
      <% end %>
    </div>
  </div>
</div>