config/routes.rb
Rails.application.routes.draw do
  get 'users/sessions'
  root to: "public/homes#top"
  get "/homes/about" => "public/homes#about", as: "about"
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  namespace :admin do
    get 'users', to: 'users#index'
    patch 'users/:id/withdraw',to: "users#withdraw", as: "users_withdraw"
    resources :tags, except: [:show]
    resources :fitness_gyms do
      resources :reviews, only: [:show, :destroy]
    end
  end

  scope module: :public do
    resources :fitness_gyms, only: [:show, :index, :create]
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end
    get 'users/unsubscribe'
    patch 'users/withdraw'
    
    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
    
    resources :users, only: [:show, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :fitness_gym
  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20 }
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
     profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
   before_action :authenticate_admin!
    def index
        @users = User.all
    end
    
    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。'
    end
    
    def withdraw
      @user = User.find(params[:id])
      @user.update(is_deleted: true)
      redirect_to admin_users_path
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h2>全ユーザー一覧</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>ユーザー名</th>
          <th>メールアドレス</th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
      <tbody>
        <tr>
          <td>
            <%= user.name %>
          </td>
          <td>
            <%= user.email %>
          </td>
          <td>
            <% if user.is_deleted == true %>
            
            <% else %>
              <%= link_to '削除', admin_users_withdraw_path(user), method: :patch, data: { confirm: '本当に削除しますか？' } %>
            <% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </ul>