config/routes.rb
Rails.application.routes.draw do
  get 'users/sessions'
  root to: "public/homes#top"
  get "/homes/about" => "public/homes#about", as: "about"
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  namespace :admin do
    get 'users', to: 'users#index'
    patch 'users/:id/withdraw',to: "users#withdraw", as: "users_withdraw"
    resources :tags, except: [:show]
    resources :fitness_gyms do
      resources :reviews, only: [:show, :destroy]
    end
  end

  scope module: :public do
    resources :fitness_gyms, only: [:show, :index, :create]
    resources :reviews do
      resources :review_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end
    get 'users/unsubscribe'
    patch 'users/withdraw'
    
    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
    
    resources :users, only: [:show, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :user_id, presence: true
end

app/models/fitness_gym.rb
class FitnessGym < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  has_many :gym_tags, dependent: :destroy
  has_many :tags, through: :gym_tags
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :content, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode

  accepts_nested_attributes_for :tags

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tags(savebook_tags)
    # 現在のユーザーの持っているskillを引っ張ってきている
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 今fitness_gymが持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
    old_tags = current_tags - savebook_tags
    # 今回保存されたものと現在の差を新しいタグとする。新しいタグは保存
    new_tags = savebook_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      gym_tag = Tag.find_or_create_by(name:new_name)
      # 配列に保存
      self.tags << gym_tag
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Fitness_gym.where(title: content)
    elsif method == 'forward'
      Fitness_gym.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Fitness_gym.where('title LIKE ?', '%'+content)
    else
      Fitness_gym.where('title LIKE ?', '%'+content+'%')
    end
  end


  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
      { id: 0, name: '--' }, { id: 1, name: '北海道' }, { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' }, { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' }, { id: 7, name: '福島県' }, { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' }, { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' }, { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' }, { id: 16, name: '富山県' }, { id: 17, name: '石川県' },
    { id: 18, name: '福井県' }, { id: 19, name: '山梨県' }, { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' }, { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' }, { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' }, { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' }, { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' }, { id: 34, name: '広島県' }, { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' }, { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' }, { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' }, { id: 43, name: '熊本県' }, { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' }, { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]

end

app/models/gym_tag.rb
class GymTag < ApplicationRecord
  belongs_to :fitness_gym
  belongs_to :tag
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :fitness_gym
  has_many :review_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validates :star, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gym_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :fitness_gyms, through: :gym_tags
  
  validates :name, presence: true

  scope :merge_fitness_gyms, -> (tags){ }
  
  def self.search_fitness_gyms_for(content, method)
    
    if method == 'perfect'
      tags = Tag.where(name: content)
    elsif method == 'forward'
      tags = Tag.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      tags = Tag.where('name LIKE ?', '%' + content)
    else
      tags = Tag.where('name LIKE ?', '%' + content + '%')
    end
    
    return tags.inject(init = []) {|result, tag| result + tag.gyms}
    
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :fitness_gym
  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20 }
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
     profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public?
    end
  end

  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end

  def action_is_public?
    controller_name == 'homes' && (action_name == 'top' || action_name == 'about')
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/fitness_gyms_helper.rb
module FitnessGymsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/review_comments_helper.rb
module ReviewCommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_admin_menu_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Fitness Gym</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to admin_fitness_gyms_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-dumbbell"></i> ジム一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_tags_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-tags"></i> タグ一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_users_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-users"></i> ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
            </ul>
          </div>
        </div>
      </nav>

app/views/layouts/_general_user_menu_bar.html.erb
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Fitness Gym</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-white' do %>
                <i class="fas fa-home"></i> ホーム
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-link"></i> アバウト
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-right-to-bracket"></i> ログイン
              <% end %>
            </li>
            </ul>
          </div>
        </div>
      </nav>

app/views/layouts/_user_menu_bar.html.erb
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Fitness Gym</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-link"></i> アバウト
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
                <i class="fa-solid fa-users"></i> ユーザー
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to fitness_gyms_path, class: 'nav-link text-white', data: {turbolinks: "false"} do %>
                <i class="fa-solid fa-book-open"></i> マップ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-white' do %>
                <i class="fas fa-home"></i> ホーム
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-link"></i> アバウト
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                <i class="fa-solid fa-right-to-bracket"></i> ログイン
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Meshiterro</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gym</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/49cf509c58.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <% if user_signed_in? %>
        <%= render 'layouts/user_menu_bar' %>
      <% elsif admin_signed_in? %>
        <%= render 'layouts/admin_menu_bar' %>
      <% else %>
        <%= render 'layouts/general_user_menu_bar' %>
      <% end %>
    </header>
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
    </div>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
</html>